name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust the Node.js version as needed

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build  # Adjust the build command as needed

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust the build output directory as needed
